apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
webhooks:
  - name: example-webhook.default.svc
    admissionReviewVersions:
      - v1
    sideEffects: None
    clientConfig:
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR3RENDQXFpZ0F3SUJBZ0lVRURsZVpSTVFCT04ranhEQ01aTGFlbEt6RW1rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2VERUxNQWtHQTFVRUJoTUNTVTR4Q3pBSkJnTlZCQWdUQWxWUU1RNHdEQVlEVlFRSEV3Vk9iMmxrWVRFUQpNQTRHQTFVRUNoTUhSWGhoYlhCc1pURVFNQTRHQTFVRUN4TUhWMlZpYUc5dmF6RW9NQ1lHQTFVRUF4TWZSWGhoCmJYQnNaU0JCWkcxcGMzTnBiMjRnUTI5dWRISnZiR3hsY2lCRFFUQWVGdzB5TmpBMU1UVXdOVEkxTURCYUZ3MHoKTVRBMU1UUXdOVEkxTURCYU1IZ3hDekFKQmdOVkJBWVRBa2xPTVFzd0NRWURWUVFJRXdKVlVERU9NQXdHQTFVRQpCeE1GVG05cFpHRXhFREFPQmdOVkJBb1RCMFY0WVcxd2JHVXhFREFPQmdOVkJBc1RCMWRsWW1odmIyc3hLREFtCkJnTlZCQU1USDBWNFlXMXdiR1VnUVdSdGFYTnphVzl1SUVOdmJuUnliMnhzWlhJZ1EwRXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREhkb0g4bk9JUmZ2b2RyNndoWjdGQUwyQzJ2cnBYL3ZONgo3MFVUcEtnbFFLTXdvQjErZ25FczlXak12UnBnR1U4NXA4emRldGQ1aXIvSlZBKzJXbmwxdE5sYmdEY2NHMUVJCkJPT05pQnlXdmRmMnBTcCtSek90WU1EVTdIckkyZU9qbXdOMDAwSGRGbDErbHFpdUdRdkxJOVd2UnAwZVp6YWwKVmFncGp2dzZMaGowbHppZGJ3Z0NOWVJTUG54bm1pMjNnajBuVFFIL0lLWVlGWTlJMlRsbHZvNTVvdmp3aDBnSQpxR0h3T0RGNnRuUnF3d3hQNUhmaitGOGVwajZTSHJjaFRFMHdYa2F2ejZyVldxMkxiV0RxYjJIanRRWllnSzZ6CkZwRDhJVHRBN0VnQmVmTWo2ZGlGZDNHc243ZmdmQlhFN1AzOGd4aU15a09RMjRQd3pEN1RBZ01CQUFHalFqQkEKTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlF2U2hCMwpzYnQ3bjR2K3ZHTVRFa0FDdjZQazdEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFkUWhLelhKUEV2WUp6WkZECmJpYytLeElyTEtHWnpzMTRsVGtWNmk5c3A0a3EwcEN2M09VNjRyWkRXM3d1azN4RFkyOFVuN0lSQnlWamFpUWoKZHA0MGJDRnkzSUZSMGt4NE1GRlBzRldaZ3o4K0x6UnZKWXBjdXI3RW54c1FoSUZqVTBIZTdTT1VzWFhMYWk3Mwo0RnN1VUxGS0VyRHdGSXNmYWszcllOTHNnRjZlUlU2cFdGSVhnKzFJcWRoZ0RrSFduSDJBakJuTlpYUW5SenRRCi9vcU40aFd4bDljZUF3dlVCZXQwYUtwR2JkdXhoNUZ4MzFDT0xPMFRic1M5M0RUZDFEN0w3dGZjWTl0bXRkMG4KaTlIaFNaR2hUWDQ1cDh3RHJqSE9pdXZiSEYwbThSdlUvTmU3dERLYitJL2VwZ1FnenVPMDFPODB5VWU0ZldoUwpEU21tUUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    failurePolicy: Ignore
